//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouBot
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int clouds = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int ChatList = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int InputContainer = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int RootLayout = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int facebookCheckBox = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int gmailCheckBox = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int input = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int learnButton = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout3 = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout4 = 2131034130;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout5 = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int message_content = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int send = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int shareButton = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int smsCheckBox = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int textView1 = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int tumblrCheckBox = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int twitterCancel = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int twitterCheckBox = 2131034119;
			
			// aapt resource value: 0x7f050014
			public const int twitterConfirm = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int twitterNameBox = 2131034129;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chat_item_him = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chat_item_you = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LearningPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TwitterPopup = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
